### ISSUE TITLE
Unable to use read-only keys

### ISSUE THREAD

**Issue by charisk** [cloud-maker-ai/Nebula#33] opened 2020-03-13 16:15 UTC
An exception is thrown when a read-only key is used.

This is because `CreateCollectionIfNotExistsAsync` in `DocumentDbService` (https://github.com/cloud-maker-ai/Nebula/blob/master/Nebula/Service/DocumentDbService.cs) doesn't check for the existence of the collection.

Exception message
```
Failed to create collection
```

Stack trace
```
   at Nebula.Service.DocumentDbService.HandleClientError(Exception e, String onErrorReason)
   at Nebula.Service.DocumentDbService.<MakeClientCall>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nebula.Service.DocumentDbService.<CreateCollectionIfNotExistsAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nebula.Service.DocumentDbService.<StartAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nebula.DocumentDbAccess.<Open>d__19.MoveNext()
```

**Comment by oughton** [comment] 2020-03-13 16:28
Nebula requires write access to the database because it owns configuration such as indexes etc. We could introduce a special read-only mode feature that would need to make some assumptions about the state of the existing database. I'm marking this as a feature request as it is by design currently.

**Closed** 2021-10-15 09:05 UTC
Labels: enhancement
